spring.application.name=Courier_Tracking_Management_System
spring.datasource.url= jdbc:postgresql://localhost:5432/Courier_Tracking_Management_System

spring.datasource.username=dbusername
spring.datasource.password=dbpass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
server.port=8081